openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger
  license:
    name: MIT
servers:
  - url: http://localhost:8081/
paths:
  /api/v1/demo:
    get:
      summary: get demo
      operationId: get demo
      tags:
        - demo
      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: string
        - name: type
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/DemoTypeDto"
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 20
        - name: sort
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: demo page
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageOfDemoDto"
    post:
      summary: post demo
      operationId: post demo
      tags:
        - demo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateDemoDto"
      responses:
        '201':
          description: demo created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DemoDto"
  /api/v1/demo/{demoId}:
    get:
      summary: get demo by id
      operationId: get demo by id
      tags:
        - demo
      parameters:
        - name: demoId
          in: path
          required: true
          description: id of demo
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: get demo by id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DemoDto"
    put:
      summary: put demo
      operationId: put demo
      tags:
        - demo
      parameters:
        - name: demoId
          in: path
          required: true
          description: The id of the base product to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateDemoDto"
      responses:
        '200':
          description: updated base product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DemoDto"
    delete:
      summary: delete demo
      operationId: delete demo
      tags:
        - demo
      parameters:
        - name: demoId
          in: path
          required: true
          description: The id of the base product to delete
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: demo deleted

components:
  schemas:
    DemoTypeDto:
      type: string
      enum:
        - ONE
        - TWO
    CreateDemoDto:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        type:
          $ref: "#/components/schemas/DemoTypeDto"
    UpdateDemoDto:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        type:
          $ref: "#/components/schemas/DemoTypeDto"
    DemoDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          $ref: "#/components/schemas/DemoTypeDto"
    PageOfDemoDto:
      type: object
      required:
        - content
      properties:
        size:
          type: integer
        number:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
        content:
          type: array
          items:
            $ref: "#/components/schemas/DemoDto"
