openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger
  license:
    name: MIT
servers:
  - url: http://localhost:8081/
paths:
  /api/v1/phrase:
    get:
      summary: get phrases by filter
      operationId: getPhrases
      tags:
        - phrase
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 20
        - name: sort
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: page of phrases
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageOfPhraseDto"
    post:
      summary: create phrase
      operationId: createPhrase
      tags:
        - phrase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePhraseRequest"
      responses:
        '201':
          description: phrase created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PhraseDto"
  /api/v1/phrase/{phraseId}:
    get:
      summary: get phrase by id
      operationId: getPhraseById
      tags:
        - phrase
      parameters:
        - name: phraseId
          in: path
          required: true
          description: id of the phrase
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: get phrase by id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PhraseDto"
    put:
      summary: update phrase
      operationId: updatePhrase
      tags:
        - phrase
      parameters:
        - name: phraseId
          in: path
          required: true
          description: The id of the phrase to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePhraseRequest"
      responses:
        '200':
          description: updated phrase
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PhraseDto"
    delete:
      summary: delete phrase
      operationId: deletePhraseById
      tags:
        - phrase
      parameters:
        - name: phraseId
          in: path
          required: true
          description: The id of the phrase to delete
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: phrase deleted
  /api/v1/tag:
    get:
      summary: get tags by filter
      operationId: getTags
      tags:
        - tag
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 20
        - name: sort
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: page of tags
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageOfTagDto"
    post:
      summary: create tag
      operationId: createTag
      tags:
        - tag
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTagRequest"
      responses:
        '201':
          description: tag created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TagDto"
  /api/v1/tag/{tagKey}:
    get:
      summary: get tag by key
      operationId: getTagByKey
      tags:
        - tag
      parameters:
        - name: tagKey
          in: path
          required: true
          description: the key of the tag
          schema:
            type: string
            minLength: 1
            maxLength: 100
            pattern: '^[0-9a-zA-Z-_]+$'
      responses:
        '200':
          description: get tag by key
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TagDto"
    put:
      summary: update tag by key
      operationId: updateTagByKey
      tags:
        - tag
      parameters:
        - name: tagKey
          in: path
          required: true
          description: the key of the tag
          schema:
            type: string
            minLength: 1
            maxLength: 100
            pattern: '^[0-9a-zA-Z-_]+$'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTagRequest"
      responses:
        '200':
          description: get tag by id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TagDto"
    delete:
      summary: delete tag by key
      operationId: deleteTagByKey
      tags:
        - tag
      parameters:
        - name: tagKey
          in: path
          required: true
          description: The key of the tag to delete
          schema:
            type: string
            minLength: 1
            maxLength: 100
            pattern: '^[0-9a-zA-Z-_]+$'
      responses:
        '200':
          description: tag deleted
components:
  schemas:
    DemoTypeDto:
      type: string
      enum:
        - ONE
        - TWO
    CreateDemoDto:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        type:
          $ref: "#/components/schemas/DemoTypeDto"
    UpdateDemoDto:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        type:
          $ref: "#/components/schemas/DemoTypeDto"
    DemoDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          $ref: "#/components/schemas/DemoTypeDto"
    PageOfDemoDto:
      type: object
      required:
        - content
      properties:
        size:
          type: integer
        number:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
        content:
          type: array
          items:
            $ref: "#/components/schemas/DemoDto"
    LangDto:
      type: string
      enum:
        - UNKNOWN
        - RU
        - FR
        - EN
    PhraseDto:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - source
        - sourceLang
        - transcription
        - target
        - targetLang
      properties:
        id:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        source:
          type: string
        sourceLang:
          $ref: "#/components/schemas/LangDto"
        transcription:
          type: string
        target:
          type: string
        targetLang:
          $ref: "#/components/schemas/LangDto"
    PageOfPhraseDto:
      type: object
      required:
        - content
      properties:
        size:
          type: integer
        number:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
        content:
          type: array
          items:
            $ref: "#/components/schemas/PhraseDto"
    CreatePhraseRequest:
      type: object
      required:
        - source
        - sourceLang
        - transcription
        - target
        - targetLang
      properties:
        source:
          type: string
        sourceLang:
          $ref: "#/components/schemas/LangDto"
        transcription:
          type: string
        target:
          type: string
        targetLang:
          $ref: "#/components/schemas/LangDto"
    UpdatePhraseRequest:
      type: object
      required:
        - id
        - source
        - sourceLang
        - transcription
        - target
        - targetLang
      properties:
        id:
          type: integer
          format: int64
        source:
          type: string
        sourceLang:
          $ref: "#/components/schemas/LangDto"
        transcription:
          type: string
        target:
          type: string
        targetLang:
          $ref: "#/components/schemas/LangDto"
    TagDto:
      type: object
      required:
        - key
      properties:
        key:
          type: string
          minLength: 1
          maxLength: 100
          pattern: '^[0-9a-zA-Z-_]+$'
    PageOfTagDto:
      type: object
      required:
        - size
        - numeber
        - totalElements
        - totalPages
        - content
      properties:
        size:
          type: integer
        number:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
        content:
          type: array
          items:
            $ref: "#/components/schemas/TagDto"
    CreateTagRequest:
      type: object
      required:
        - key
      properties:
        key:
          type: string
          minLength: 1
          maxLength: 100
          pattern: '^[0-9a-zA-Z-_]+$'
        lesson_id:
          type: integer
          format: int64
    UpdateTagRequest:
      type: object
      required:
        - newKey
      properties:
        newKey:
          type: string
          minLength: 1
          maxLength: 100
          pattern: '^[0-9a-zA-Z-_]+$'

